sudo: false

language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"  
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

matrix:
  include:
  - addons:
      mariadb: "5.5"
    NAME="MariaDB 5.5/Perl 5.24"
    perl: "5.24"
  - addons:
      mariadb: "10.0"
    NAME="MariaDB 10.0/Perl 5.24"
    perl: "5.24"
  - addons:
      mariadb: "10.1"
    NAME="MariaDB 10.1/Perl 5.24"
    perl: "5.24"
  - addons:
      mariadb: "10.2"
    NAME="MariaDB 10.2/Perl 5.24"
    perl: "5.24"
  - addons:
      mysql: "5.5"
    NAME="MySQL 5.5/Perl 5.24"
    perl: "5.24"
  - addons:
      mysql: "5.6"
    NAME="MySQL 5.6/Perl 5.24"
    perl: "5.24"
  - addons:
      mysql: "5.7"
    NAME="MySQL 5.7/Perl 5.24"
    perl: "5.24" 
  - addons:
      mysql: "8"
    NAME="MySQL 8/Perl 5.24"
    perl: "5.24"
  - addons:
      mariadb: "5.5"
    NAME="MariaDB 5.5/Perl 5.10"
    perl: "5.10"
  - addons:
      mariadb: "10.0"
    NAME="MariaDB 10.0/Perl 5.10"
    perl: "5.10"
  - addons:
      mariadb: "10.1"
    NAME="MariaDB 10.1/Perl 5.10"
    perl: "5.10"
  - addons:
      mariadb: "10.2"
    NAME="MariaDB 10.2/Perl 5.10"
    perl: "5.10"
  - addons:
      mysql: "5.5"
    NAME="MySQL 5.5/Perl 5.10"
    perl: "5.10"
  - addons:
      mysql: "5.6"
    NAME="MySQL 5.6/Perl 5.10"
    perl: "5.10"
  - addons:
      mysql: "5.7"
    NAME="MySQL 5.7/Perl 5.10"
    perl: "5.10" 
  - addons:
      mysql: "8"
    NAME="MySQL 8/Perl 5.10"
    perl: "5.10"
       
before_install:
  - git clone git://github.com/haarg/perl-travis-helper
  - source perl-travis-helper/init
  - build-perl
  - perl -V

install:
  - cpanm --quiet --notest Data::Dumper
  - cpanm --quiet --notest JSON
  - cpanm --quiet --notest Perl::Critic
  - cpanm --quiet --notest Text::Template

before_script:
  - echo -e "[client]\nuser=root\npassword=\"\"" > .my.cnf
  - chmod 600 .my.cnf
  - wget "https://launchpad.net/test-db/employees-db-1/1.0.6/+download/employees_db-full-1.0.6.tar.bz2"
  - tar xvjf employees_db-full-1.0.6.tar.bz2
  - cd employees_db
  - cat employees.sql | mysql
  - cd ..

script:
  - perlcritic --exclude InputOutput::ProhibitInteractiveTest mysqltuner.pl
  - ./mysqltuner.pl --verbose --tbstat
